#!/usr/bin/env ruby

services = %w(rails mongod memcached redis-server sidekiq)

puts "Killing any of the following processes: #{services.join(", ")}"

system("sudo killall {#{services.join(",")}} 2> /dev/null")